cd ~/sphenix/single/SinglePhotonAfter/build
make install
cd ../../PhotonConversion/build
make install
cd ../../ClusterShape/build
make install
cd ../truthconversion/build/
make install
cd ../../condor
